apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base/multiapp
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      name: multiapp
namespace: ns1
